"""Default configuration template used by `securedeploy init`."""

INIT_TEMPLATE = """\
# securedeploy.yaml — generated by `securedeploy init`
# Documentation: https://github.com/securedeploy/securedeploy

version: "1"

project:
  name: "{project_name}"

target:
  url: "https://staging.{domain}"
  environment: staging

source:
  path: "./src"
  exclude:
    - "node_modules/"
    - "vendor/"
    - ".git/"
    - "**/*.min.js"

testing:
  source_code: true
  secrets: true
  dependencies: true
  containers: false     # set to true and configure container_images below
  tls: true
  headers: true
  web: true
  api: true
  network: false        # requires Nmap installed separately
  custom_tests: true
  container_images: []
  iac_paths: []

custom_tests:
  paths:
    - "./security-tests/**/*.yaml"

policy:
  on_finding:
    critical: block
    high: block
    medium: warn
    low: report
    informational: report
  on_tool_failure: warn

# accepted_risks:
#   - id: "AR-001"
#     title: "Self-signed cert on staging"
#     rule_id: "ssl-cert-self-signed"
#     tool: "builtin"
#     reason: "Staging uses self-signed cert. Production has a valid cert."
#     accepted_by: "security@example.com"
#     expires: "2027-01-01"

safety:
  max_concurrency: 3
  default_timeout: 600
  max_requests_per_second: 10

output:
  directory: "./securedeploy-reports"
  formats:
    - terminal
    - sarif
    - json
"""

IDENTITIES_TEMPLATE = """\
# security-tests/identities.yaml
# Define application identities used by custom security tests.
# Credentials must come from environment variables — never hardcode them here.

identities:

  - id: "unauthenticated"
    # No auth — represents an anonymous request

  # Example: bearer token via login endpoint
  # - id: "regular_user"
  #   auth:
  #     type: "login_form"
  #     url: "/api/auth/login"
  #     method: "POST"
  #     body:
  #       username: "${{TEST_USER_EMAIL}}"
  #       password: "${{TEST_USER_PASSWORD}}"
  #     token_path: "$.access_token"
  #     token_usage:
  #       header: "Authorization"
  #       prefix: "Bearer "

  # Example: API key
  # - id: "admin"
  #   auth:
  #     type: "api_key"
  #     header: "X-API-Key"
  #     value: "${{TEST_ADMIN_API_KEY}}"
"""

AUTHORIZATION_TEMPLATE = """\
# security-tests/authorization.yaml
# Define application-specific authorization tests.
# These tests verify that your access control rules are correctly enforced.

suite: "Authorization and Access Control"
category: "Broken Access Control"
owasp: "WSTG-ATHZ-01"
cwe: "CWE-285"

authorization_tests: []

# Example — uncomment and adapt:
#
#   - name: "Unauthenticated request cannot access authenticated endpoints"
#     severity: critical
#     identity: "unauthenticated"
#     request:
#       method: GET
#       path: /api/profile
#     expect:
#       status: [401, 403]
#
#   - name: "Regular user cannot access admin API"
#     severity: critical
#     identity: "regular_user"
#     request:
#       method: GET
#       path: /api/admin/users
#     expect:
#       status: [403, 404]
"""
